/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjetoRouteImport } from './routes/projeto'
import { Route as IndexRouteImport } from './routes/index'

const ProjetoRoute = ProjetoRouteImport.update({
  id: '/projeto',
  path: '/projeto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projeto': typeof ProjetoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projeto': typeof ProjetoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projeto': typeof ProjetoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projeto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projeto'
  id: '__root__' | '/' | '/projeto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjetoRoute: typeof ProjetoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projeto': {
      id: '/projeto'
      path: '/projeto'
      fullPath: '/projeto'
      preLoaderRoute: typeof ProjetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjetoRoute: ProjetoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
