/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjetoRouteImport } from './routes/projeto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPoeChatRouteImport } from './routes/api/poe-chat'

const ProjetoRoute = ProjetoRouteImport.update({
  id: '/projeto',
  path: '/projeto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPoeChatRoute = ApiPoeChatRouteImport.update({
  id: '/api/poe-chat',
  path: '/api/poe-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projeto': typeof ProjetoRoute
  '/api/poe-chat': typeof ApiPoeChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projeto': typeof ProjetoRoute
  '/api/poe-chat': typeof ApiPoeChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projeto': typeof ProjetoRoute
  '/api/poe-chat': typeof ApiPoeChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projeto' | '/api/poe-chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projeto' | '/api/poe-chat'
  id: '__root__' | '/' | '/projeto' | '/api/poe-chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjetoRoute: typeof ProjetoRoute
  ApiPoeChatRoute: typeof ApiPoeChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projeto': {
      id: '/projeto'
      path: '/projeto'
      fullPath: '/projeto'
      preLoaderRoute: typeof ProjetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/poe-chat': {
      id: '/api/poe-chat'
      path: '/api/poe-chat'
      fullPath: '/api/poe-chat'
      preLoaderRoute: typeof ApiPoeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjetoRoute: ProjetoRoute,
  ApiPoeChatRoute: ApiPoeChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
